name = "MESTI"
uuid = "8d7f31fa-9986-4e1d-8c81-72752476e54d"
license = "GPL-3.0"
authors = ["Ho-Chun Lin<hochunlin0508@gmail.com>, Shiyu Li, Zeyu Wang, and Chia Wei Hsu<cwhsu@usc.edu>"]
version = "0.3.0"

[deps]
GeometryPrimitives = "17051e67-205e-509e-8301-03b320b998e6"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"

[compat]
GeometryPrimitives = "0.4.6"
LazyGrids = "0.5.0"
Libdl = "<0.0.1, 1"
LinearAlgebra = "<0.0.1, 1"
MPI = "0.20.16"
Printf = "<0.0.1, 1"
Random = "<0.0.1, 1"
SparseArrays = "<0.0.1, 1"
StaticArrays = "1.7.0"
Statistics = "<0.0.1, 1"
TensorCast = "0.4.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
